<?php

namespace Loisirs\LoisirsBundle\Repository;

/**
 * BonplanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonplanRepository extends \Doctrine\ORM\EntityRepository
{

    public function findBonplan($p){
        $query=$this->getEntityManager()->createQuery(
            "select m from LoisirsLoisirsBundle:Bonplan m WHERE m.region like :p"
        )->setParameter('p','%'.$p.'%');
        return $query->getResult();
    }

}
