<?php

namespace DonateBundle\Repository;

/**
 * ProduitDonationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitDonationRepository extends \Doctrine\ORM\EntityRepository
{

/*    function findSerieDQL($nom){
        $query=$this->getEntityManager()
            ->createQuery("select v from DonateBundle v WHERE v.nom 
LIKE :nom  ")
            ->setParameter('nom','%'.$nom.'%');
        return $query->getResult();



    }*/

    public function findAjaxD($search)
    {/*$date_from = new \DateTime('now');
        ->setParameter('date_from', $date_from)
        ->andWhere('e.datedeb > = :date_form')*/

        return $this->createQueryBuilder('e')
            ->andWhere('e.nom LIKE :nom')
            ->orWhere('e.nomuser LIKE :nom')
            ->orWhere('e.adresse LIKE :nom')
            ->setParameter('nom','%' .$search . '%')
            ->getQuery()
            ->getResult();
    }
}
