<?php

namespace Enseignant\EnseignantBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{


    function findBook($p)
    {
        $query=$this->getEntityManager()->createQuery(
            "select m from EnseignantEnseignantBundle:Book m WHERE m.nomauteur LIKE :p")->setParameter('p','%'.$p.'%');
        return $query->getResult();

    }

}
