# app / config / routing.yml
# app/config/routing.yml
user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook
google_login:
      path: /login/check-google

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

FindAllUser:
    path:     /AllUser
    defaults: { _controller: UserBundle:Default:user_all }
FindUserName:
     path:     /Username/{username}
     defaults: { _controller: UserBundle:Default:find_username }