<?php

namespace Sante\SpecialisteBundle\Repository;

/**
 * reponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reponseRepository extends \Doctrine\ORM\EntityRepository
{
    function nbreponse($idparent)
    {
        $etat=1;
        $query = $this->getEntityManager()
            ->createQuery(" 
    select count(s) as nb from SanteSpecialisteBundle:reponse s 
    WHERE  s.idparent LIKE :idparent 
      ")->setParameter('idparent', '%' . $idparent . '%');
        return $query->getResult();
    }
}
