<?php

namespace Sante\SpecialisteBundle\Repository;

/**
 * traitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class traitementRepository extends \Doctrine\ORM\EntityRepository
{
}
