<?php

namespace BabyBundle\Repository;

/**
 * AvisbabyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisbabyRepository extends \Doctrine\ORM\EntityRepository
{


//    function findSerieDQL($nom)
//    {
//        $query = $this->getEntityManager()
//            ->createQuery("select v from EventsBundle:Evenement v WHERE v.nom LIKE :nom ")
//            ->setParameter('nom', '%' . $nom . '%');
//        return $query->getResult();
//
//
//    }


    public function findByiduetidb($idu,$idb)
{
    $query = $this->getEntityManager()->createQuery("SELECT avis FROM BabyBundle:Avisbaby avis WHERE avis.idu = :idub AND avis.idb = :idbb");
    $query->setParameters(array(
        'idub' => $idu,
        'idbb' => $idb,
    ));
    return $query->getResult();
}



    public function findBynbrlike($idb)
{
    $query = $this->getEntityManager()->createQuery("SELECT avis FROM BabyBundle:Avisbaby avis WHERE avis.nbrlike = :nbrlike AND avis.idb = :idbb");
    $query->setParameters(array(
        'nbrlike' => 1,
        'idbb' => $idb,
    ));
    return $query->getResult();
}



    public function findBynbrdislike($idb)
{
    $query = $this->getEntityManager()->createQuery("SELECT avis FROM BabyBundle:Avisbaby avis WHERE avis.nbrdislike = :nbrdislike AND avis.idb = :idbb");
    $query->setParameters(array(
        'nbrdislike' => 1,
        'idbb' => $idb,
    ));
    return $query->getResult();
}







}
